import { Column, Entity, Index, PrimaryColumn } from 'typeorm';
import { createHash } from 'node:crypto';
import { UniversalCreateDateColumn } from '../common/decorators/universal-date-column';

/**
 * One row per thing that happened to a project, so a turn has an identity.
 *
 * The problem this exists to solve: a version sha carries no chat, no user, no
 * model and no prompt — only a 72-character label — so "which turns were bad"
 * is unanswerable no matter how many events are logged. A restore is a human
 * verdict nobody asked the agent for, and it is already on disk as a commit;
 * it just points at a sha that joins to nothing. This row is that join key.
 *
 * ONE WIDE TABLE, on purpose. The repo carries no migrations and relies on
 * `synchronize` (database.config.ts), so every new entity costs a deliberate
 * DB_SYNCHRONIZE=true production deploy against a database where synchronize
 * will drop columns to match the entities. A second table later is a second
 * such deploy. So restores and outcome events become rows here too,
 * discriminated by `kind`, and their columns are defined now and written
 * later. Nullable is free; a second synchronize deploy is not.
 *
 * Not a GraphQL @ObjectType: nothing in the product reads this. It is written
 * by the backend and read by a digest, and exposing it would make prompts and
 * user ids queryable from the browser.
 */
export type AgentTurnKind =
  | 'turn'
  | 'restore'
  | 'publish'
  | 'share'
  | 'download'
  | 'fork'
  /** Not an event: one row per distinct instructions string, see instructionsHash. */
  | 'template';

@Entity()
export class AgentTurn {
  /**
   * Minted in `runTurn` before anything can fail, NOT generated by the
   * database: the rescue-save path needs the id while the turn is still
   * running. For a `kind: 'template'` row this is the instructions hash
   * instead, which is what makes first-sight upsert idempotent.
   */
  @PrimaryColumn('varchar')
  id: string;

  @Column({ default: 'turn' })
  @Index()
  kind: AgentTurnKind;

  @UniversalCreateDateColumn()
  createdAt: Date;

  // --- who and what -------------------------------------------------------

  @Column({ nullable: true })
  @Index()
  chatId: string | null;

  /**
   * The user who typed, from the request — NOT project.userId. On a shared or
   * forked project the owner is not the person driving the turn, and
   * attributing their turns to the owner is how "which users get rejected
   * turns" answers itself wrong.
   */
  @Column({ nullable: true })
  @Index()
  userId: string | null;

  @Column({ nullable: true })
  @Index()
  projectPath: string | null;

  @Column({ nullable: true })
  projectId: string | null;

  @Column({ nullable: true })
  template: string | null;

  @Column({ nullable: true })
  scenarioId: string | null;

  /**
   * The model this turn actually ran on, from the request DTO. The only
   * correct per-turn record: `Chat.model` is mutable (updateChatModel) and the
   * DTO overrides it per request, so a chat that switched models mid-project
   * reports every earlier turn under the new model.
   */
  @Column({ nullable: true })
  model: string | null;

  /** Which CLI ran it — 'codex' or 'claude-code' are not interchangeable. */
  @Column({ nullable: true })
  harness: string | null;

  /**
   * The user brought their own endpoint. A boolean and nothing else: the key
   * and base URL are never stored, never logged (see ChatRestDto). It is
   * recorded at all because a BYOK turn ran on a model list we do not control,
   * so `model` means something different for it.
   */
  @Column({ default: false })
  byok: boolean;

  // --- the git join -------------------------------------------------------

  /**
   * The commit this turn produced, or null when it changed no files — which
   * since host-workspace.ts gates on `git status --porcelain` is a trustworthy
   * "this turn wrote nothing", not a failure. A turn that only answered a
   * question legitimately has no sha.
   */
  @Column({ nullable: true })
  @Index()
  sha: string | null;

  /** HEAD before the turn, so the rolled-back range is computable. */
  @Column({ nullable: true })
  parentSha: string | null;

  /** The `Your edits` commit, when the user hand-fixed the previous output. */
  @Column({ nullable: true })
  handEditSha: string | null;

  // --- session position ---------------------------------------------------

  /** How many stored messages preceded this turn. */
  @Column({ nullable: true })
  turnIndex: number | null;

  @Column({ nullable: true })
  messageId: string | null;

  /** How many prior turns the prompt actually replayed, after clipping. */
  @Column({ nullable: true })
  historyTurns: number | null;

  // --- the prompt ---------------------------------------------------------

  /**
   * sha256 of the instructions, first 12 hex chars. Hashed rather than stored
   * because template × scenario is a few dozen distinct strings in total; the
   * text itself lives once, in a `kind: 'template'` row keyed by this hash.
   */
  @Column({ type: 'varchar', length: 12, nullable: true })
  @Index()
  instructionsHash: string | null;

  /** sha256 of the exact prompt string sent, first 12 hex chars. */
  @Column({ type: 'varchar', length: 12, nullable: true })
  promptHash: string | null;

  @Column({ nullable: true })
  promptChars: number | null;

  /** The instruction half of an (instruction, output) pair, verbatim. */
  @Column({ type: 'text', nullable: true })
  userMessage: string | null;

  /**
   * The parts of the prompt that are NOT reconstructible from what we already
   * store: notes, hand edits, lint findings, image count.
   *
   * Deliberately NOT the retold history. That is a deterministic function of
   * Chat.messages, which we have — storing it would copy the whole
   * conversation into every turn's row and grow quadratically with chat
   * length. It is the single biggest bloat risk here, so it is the one thing
   * left out.
   *
   * Images are a COUNT and nothing else. A screenshot is the most likely place
   * in this product for personal data nobody can redact.
   */
  @Column('simple-json', { nullable: true })
  contextJson: TurnContext | null;

  // --- the outcome --------------------------------------------------------

  @Column({ type: 'text', nullable: true })
  reply: string | null;

  @Column('simple-json', { nullable: true })
  steps: unknown[] | null;

  @Column({ nullable: true })
  stepCount: number | null;

  @Column({ nullable: true })
  toolCalls: number | null;

  @Column({ default: false })
  errored: boolean;

  @Column({ type: 'text', nullable: true })
  errorText: string | null;

  /** The client hung up mid-turn. The highest-value negative sample there is. */
  @Column({ default: false })
  abandoned: boolean;

  @Column({ nullable: true })
  durationMs: number | null;

  // --- the verdict, written later by the digest ---------------------------

  /** 'rejected' | 'patched' | 'retried' | 'survived'. Nothing writes it yet. */
  @Column({ nullable: true })
  verdict: string | null;

  /** What a `kind: 'restore'` row restored TO. Nothing writes it yet. */
  @Column({ nullable: true })
  targetSha: string | null;
}

/** The non-reconstructible half of a prompt. See AgentTurn.contextJson. */
export interface TurnContext {
  notes?: string | null;
  handEdits?: { path: string; status: string }[];
  lint?: unknown[];
  /** Count only — never the bytes, never the content. */
  images?: number;
}

/** The 12 hex chars every hash column in this table holds. */
export const hash12 = (value: string): string =>
  createHash('sha256').update(value).digest('hex').slice(0, 12);
