coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
        branches:
          - main
        if_ci_failed: error
        informational: false
        only_pulls: false
    patch:
      default:
        target: auto
        threshold: 1%
        base: auto
        if_ci_failed: error
        only_pulls: false

comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false
  show_carryforward_flags: true
  after_n_builds: 1

github_checks:
  annotations: true
