#!/usr/bin/env node
// Generates the .env files a local dev run needs, once. Idempotent: an
// existing file is never touched, so your keys survive.
// ponytail: no templating engine, no prompts — two literals and randomBytes.
import { randomBytes } from 'node:crypto';
import { existsSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const secret = () => randomBytes(32).toString('hex');

const files = {
  'backend/.env': () => `# Generated by scripts/dev-init.mjs — safe to edit.
PORT=8080
NODE_ENV="DEV"

JWT_SECRET="${secret()}"
JWT_REFRESH="${secret()}"
SALT_ROUNDS=10

# Leave DATABASE_URL unset to use the zero-setup SQLite file at
# .codefox/data/codefox.db. Set a postgres:// URL to switch.
# DATABASE_URL="postgresql://postgres:postgres@localhost:5432/codefox"

# LLM backend. Either get an OpenRouter key at https://openrouter.ai/keys:
OPENROUTER_API_KEY=""

# ...or point at any local OpenAI-compatible endpoint to run against your
# already-logged-in Claude / Codex CLIs, no cloud key needed. Model ids must
# match what that endpoint serves.
# LLM_BASE_URL="http://127.0.0.1:8317/v1"
# LLM_API_KEY="local"
# LLM_MODELS="claude-sonnet-5,gpt-5.3-codex-spark"

MAIL_ENABLED=false
GITHUB_ENABLED=false
`,
  'frontend/.env': () => `NEXT_PUBLIC_GRAPHQL_URL=http://localhost:8080/graphql
`,
};

let wrote = 0;
for (const [rel, build] of Object.entries(files)) {
  const path = join(root, rel);
  if (existsSync(path)) continue;
  writeFileSync(path, build(), { mode: 0o600 });
  console.log(`created ${rel}`);
  wrote++;
}

if (wrote) {
  console.log('\nSet OPENROUTER_API_KEY in backend/.env before using chat.\n');
} else {
  console.log('env files already present — nothing to do');
}
