'use client';

import { useRef, useContext, useState } from 'react';
import Image from 'next/image';
import { motion } from 'framer-motion';
import { AuthChoiceModal } from '@/components/auth-choice-modal';
import { useAuthContext } from '@/providers/AuthProvider';
import { PromptForm, PromptFormRef } from '@/components/root/prompt-form';
import { ProjectContext } from '@/components/chat/code-engine/project-context';
import { SignInModal } from '@/components/sign-in-modal';
import { SignUpModal } from '@/components/sign-up-modal';
import { Workbench } from '@/components/root/workbench';
import { PublicProjects } from '@/components/root/public-projects';
import { useRouter } from 'next/navigation';
import { logger } from '../log/logger';

/**
 * The signed-out landing page.
 *
 * Everything stated here is something the product actually does — the tool
 * sequence, the file counts and the diff below are from a recorded run, not
 * illustrative copy.
 */

const TOOL_CALLS = [
  { tool: 'read', target: 'src/app/page.tsx', result: '74 lines' },
  { tool: 'bash', target: 'ls src/components', result: '42 parts' },
  { tool: 'read', target: 'mode-toggle.tsx', result: 'reused' },
  { tool: 'grep', target: '"ModeToggle"', result: '2 hits' },
  { tool: 'edit', target: 'src/app/page.tsx', result: '+12 −5' },
  { tool: 'edit', target: 'src/app/page.tsx', result: '+3 −0' },
];

const FACTS = [
  {
    n: '365',
    title: 'files in the app starter',
    hint: 'Next.js 15 + shadcn — or a one-file HTML page, your pick',
    accent: true,
  },
  {
    n: '1',
    title: 'dependency install, ever',
    hint: '629 packages cached once, shared by every project',
  },
  {
    n: '0',
    title: 'cloud keys required',
    hint: 'Any OpenAI- or Anthropic-compatible endpoint works',
  },
];

const LIMITS = [
  {
    title: 'The sandbox is not isolation',
    tag: 'by design',
    body: 'The agent runs with the backend process privileges inside a scoped directory. That is the trade for using the CLI you are already signed into. Swap in a network sandbox provider for anything untrusted — same interface.',
  },
  {
    title: 'Projects share one node_modules',
    tag: 'known',
    body: 'Every project comes from the same template, so they symlink a single install. That stops being true the moment the agent is allowed to add a dependency.',
  },
  {
    title: 'Two starters, not a marketplace',
    tag: 'known',
    body: 'A project is either a self-contained HTML page or a Next.js app — you pick at creation. The scaffolder takes a git URL, so further starters are configuration rather than code.',
  },
];

function Chip({ children }: { children: React.ReactNode }) {
  return (
    <span className="rounded-md border border-border bg-card/60 px-2.5 py-1.5 font-mono text-[11px] uppercase tracking-[0.08em] text-muted-foreground backdrop-blur">
      {children}
    </span>
  );
}

export default function HomePage() {
  const [showAuthChoice, setShowAuthChoice] = useState(false);
  const router = useRouter();
  const [showSignIn, setShowSignIn] = useState(false);
  const [showSignUp, setShowSignUp] = useState(false);

  const promptFormRef = useRef<PromptFormRef>(null);
  const { isAuthorized } = useAuthContext();
  const { createProjectFromPrompt, isLoading } = useContext(ProjectContext);

  const handleSubmit = async () => {
    if (!promptFormRef.current) return;

    const { message, isPublic, model, scenario, style } =
      promptFormRef.current.getPromptData();
    if (!message.trim()) return;

    try {
      const chatId = await createProjectFromPrompt(
        message,
        isPublic,
        model,
        scenario,
        style
      );
      if (!chatId) return; // createProjectFromPrompt already surfaced the error

      promptFormRef.current.clearMessage();
      router.push(`/chat?id=${chatId}`);
    } catch (error) {
      logger.error('Error creating project:', error);
    }
  };

  // Signed in? Skip the pitch — go straight to the composer and your work.
  if (isAuthorized) {
    return (
      <Workbench
        promptFormRef={promptFormRef}
        onSubmit={handleSubmit}
        isLoading={isLoading}
      />
    );
  }

  return (
    <div className="relative overflow-x-clip">
      {/* ---------- hero ---------- */}
      <section className="relative">
        {/* Painted hero: a Roman aqueduct in classical-oil-painting light that
            dissolves into ASCII glyphs at the bottom — the glyphs are only "f"
            and "x" (fox), the 11X "1"/"x" trick with our own name. Generated by
            scripts/ascii-hero.mjs over a codex-made painting; it fades to warm
            paper, so light theme gets it full-strength and dark theme dims it
            to a glow instead of hiding it. */}
        <div
          aria-hidden
          className="pointer-events-none absolute inset-x-0 -top-32 h-[1330px] bg-[url(/hero-aqueduct.jpg)] bg-cover bg-[position:70%_30%] opacity-90 dark:opacity-30
                     [mask-image:linear-gradient(180deg,#000_0%,#000_48%,transparent_96%)]"
        />
        <div
          aria-hidden
          className="pointer-events-none absolute inset-x-0 top-0 h-[780px] opacity-[0.05]
                     [background-image:linear-gradient(currentColor_1px,transparent_1px),linear-gradient(90deg,currentColor_1px,transparent_1px)]
                     [background-size:62px_62px]
                     [mask-image:radial-gradient(ellipse_85%_55%_at_45%_0%,#000_25%,transparent_78%)]"
        />
        <div
          aria-hidden
          className="pointer-events-none absolute inset-x-0 -top-24 h-[620px]
                     bg-[radial-gradient(ellipse_55%_45%_at_25%_0%,hsl(var(--primary)/0.16),transparent_70%)]"
        />

        {/* The composer used to live in the left column, which made that column
            643px tall against the shot's 362px — vertically centred, the shot
            floated with 140px of nothing above and below it. The shot cannot
            grow to match without either overflowing the row or cropping the app
            out of its own screenshot, so the composer moved out instead: the
            row is now headline against shot, which are close in height, and the
            composer spans the full width below, where it is also a better
            target than a half-width box. */}
        <div className="relative mx-auto grid w-full max-w-[1180px] gap-12 px-5 pt-12 sm:px-10 lg:grid-cols-[1.15fr_1fr] lg:items-center lg:gap-8 lg:pt-20">
          <motion.div
            initial={{ opacity: 0, y: 14 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
          >
            <div className="mb-7 flex flex-wrap gap-2">
              <Chip>Local-first</Chip>
              <Chip>Claude Code inside</Chip>
              <Chip>MIT</Chip>
            </div>

            <h1 className="font-display text-[clamp(2.5rem,5vw,4rem)] font-bold leading-[1.02] tracking-[-0.035em] text-foreground">
              One prompt.
              <br />A repo that{' '}
              <span className="text-primary">already runs</span>.
            </h1>

            <p className="mt-6 max-w-[54ch] text-[1.0625rem] leading-relaxed text-muted-foreground">
              CodeFox scaffolds a real Next.js project on your disk, points
              Claude Code at it, and boots a dev server beside the chat. Not a
              preview of code — the code, on a port, in your browser.
            </p>
          </motion.div>

          {/* Real product, not an illustration. It used to be pulled past the
              container's right edge, which left 170px of margin on the left of
              the row and 11px on the right — the shot ended up crowding the
              window while the text side kept its air. It stays inside the
              container so both sides of the row are measured the same. */}
          <motion.div
            className="relative"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.1, ease: [0.16, 1, 0.3, 1] }}
          >
            {/* No fake window chrome around it: the shot already contains the
                product's own toolbar and address bar, so the dots and the
                title bar made a frame around a frame. */}
            <div className="overflow-hidden rounded-xl border border-border bg-card shadow-2xl">
              <Image
                src="/demo/product-shot.png"
                alt="A generated analog-synth sound designer running inside CodeFox preview"
                width={1600}
                height={1147}
                className="block h-auto w-full"
                priority
              />
            </div>
          </motion.div>
        </div>

        <motion.div
          className="relative mx-auto w-full max-w-[1180px] px-5 pb-20 pt-10 sm:px-10 lg:pb-28"
          initial={{ opacity: 0, y: 14 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.15, ease: [0.16, 1, 0.3, 1] }}
        >
          <div className="rounded-xl border border-border bg-card">
            <PromptForm
              ref={promptFormRef}
              isAuthorized={isAuthorized}
              onSubmit={handleSubmit}
              onAuthRequired={() => setShowAuthChoice(true)}
              isLoading={isLoading}
              compact
            />
          </div>

          <p className="mt-4 font-mono text-xs text-muted-foreground">
            Node 18+ · no database to install · no cloud API key
          </p>
        </motion.div>
      </section>

      {/* ---------- the numbers ---------- */}
      <section className="mx-auto w-full max-w-[1180px] px-5 pb-16 sm:px-10">
        <div className="grid gap-8 pt-8 sm:grid-cols-3">
          {FACTS.map((f) => (
            <div key={f.title}>
              <p
                className={`font-display text-[clamp(2.25rem,4vw,3rem)] font-bold leading-none tracking-[-0.04em] ${
                  f.accent ? 'text-primary' : 'text-foreground'
                }`}
              >
                {f.n}
              </p>
              <p className="mt-2 text-[1.0625rem] font-bold tracking-[-0.015em] text-foreground">
                {f.title}
              </p>
              <p className="mt-1 font-mono text-xs text-muted-foreground">
                {f.hint}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* ---------- one real turn ----------
          Separated by air and typography, not by a band. Two earlier attempts
          failed the same way: `bg-foreground` dropped a light slab into a dark
          page (and broke every `text-primary` child inside it), and
          `bg-secondary` is a near-neutral grey that reads as dirt under the
          warm painted hero. The label, the display heading and the bordered
          cards do the separating. */}
      <section className="py-28">
        <div className="mx-auto w-full max-w-[1180px] px-5 sm:px-10">
          <p className="mb-6 font-mono text-[11px] uppercase tracking-[0.14em] text-primary">
            One turn, start to finish
          </p>

          {/* One phrase, set as one phrase. It used to be pushed apart to the
              two ends of the row with vertical type between the halves, which
              at this width put 900px between two words that have to be read
              together — the gap read as a layout bug, not as emphasis. */}
          <div className="mb-10 flex flex-wrap items-end justify-between gap-x-8 gap-y-3">
            <h2 className="font-display text-[clamp(2rem,6vw,4.25rem)] font-bold leading-[0.9] tracking-[-0.04em]">
              Reset Streaks
            </h2>
            <p className="font-mono text-xs opacity-60">
              the whole prompt: “Add a Reset Streaks button under the weekly
              summary.”
            </p>
          </div>

          <div className="grid gap-10 lg:grid-cols-2">
            <div>
              <p className="mb-3 font-mono text-[11px] uppercase tracking-[0.12em] opacity-50">
                What the agent did
              </p>
              <div className="rounded-xl border border-border">
                {TOOL_CALLS.map((c, i) => (
                  <div
                    key={`${c.tool}-${i}`}
                    className={`grid grid-cols-[4.5rem_1fr_auto] items-center gap-3 px-4 py-2.5 font-mono text-xs ${
                      i > 0 ? 'border-t border-border' : ''
                    }`}
                  >
                    <span className="text-primary">{c.tool}</span>
                    <span className="truncate">{c.target}</span>
                    <span className="opacity-55">{c.result}</span>
                  </div>
                ))}
              </div>
              <p className="mt-3 font-mono text-xs opacity-55">
                6 calls · 1 file touched · no scaffolding rewritten
              </p>
            </div>

            <div>
              <p className="mb-3 font-mono text-[11px] uppercase tracking-[0.12em] opacity-50">
                What changed on disk
              </p>
              <pre className="overflow-x-auto rounded-xl border border-border p-4 font-mono text-xs leading-[1.9]">
                <span className="opacity-50">src/app/page.tsx</span>
                {'\n'}
                <span className="text-primary">+ &apos;use client&apos;;</span>
                {'\n'}
                <span className="text-primary">
                  + import {'{'} useState {'}'} from &apos;react&apos;;
                </span>
                {'\n\n'}
                <span className="opacity-45">- const habits: Habit[] = [</span>
                {'\n'}
                <span className="text-primary">
                  + const initialHabits: Habit[] = [
                </span>
                {'\n\n'}
                <span className="text-primary">
                  + const [habits, setHabits] = useState(initialHabits);
                </span>
                {'\n'}
                <span className="text-primary">
                  + const resetStreaks = () =&gt;
                </span>
              </pre>
              <p className="mt-3 font-mono text-xs opacity-55">
                It found the template&apos;s existing ModeToggle and reused it
                instead of writing a new one.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* The showcase sits here rather than below the small print: it is the
          only place a visitor sees what the thing actually produces, and it is
          the one section made of pictures in a page that is otherwise text. */}
      <div className="mx-auto w-full max-w-[1180px] px-5 pt-4 sm:px-10">
        <PublicProjects limit={6} />
      </div>

      {/* ---------- honest limits ----------
          Two columns, because one narrow column of prose in a 1180px shell
          leaves the right two thirds of the section empty. The heading holds
          the left rail and sticks while the list scrolls past it. */}
      <section className="mx-auto grid w-full max-w-[1180px] gap-x-14 gap-y-8 px-5 py-24 sm:px-10 lg:grid-cols-[minmax(0,20rem)_1fr]">
        <div className="lg:sticky lg:top-24 lg:self-start">
          <p className="mb-4 font-mono text-[11px] uppercase tracking-[0.14em] text-primary">
            Read this before you star it
          </p>
          <h2 className="text-balance font-display text-[clamp(1.75rem,3.4vw,2.5rem)] font-bold leading-[1.08] tracking-[-0.025em] text-foreground">
            What it does not do yet.
          </h2>
        </div>

        <div className="overflow-hidden rounded-xl border border-border">
          {LIMITS.map((l, i) => (
            <details
              key={l.title}
              className={`p-5 ${i > 0 ? 'border-t border-border' : ''}`}
            >
              <summary className="flex cursor-pointer list-none items-center gap-3 [&::-webkit-details-marker]:hidden">
                <span className="font-mono text-primary transition-transform">
                  ›
                </span>
                <span className="text-[1.0625rem] font-bold tracking-[-0.015em] text-foreground">
                  {l.title}
                </span>
                <span className="ml-auto shrink-0 rounded-full border border-border px-2 py-0.5 font-mono text-[10px] uppercase tracking-[0.06em] text-muted-foreground">
                  {l.tag}
                </span>
              </summary>
              <p className="mt-3 max-w-[70ch] pl-7 text-[0.9375rem] leading-relaxed text-muted-foreground">
                {l.body}
              </p>
            </details>
          ))}
        </div>
      </section>

      {/* ---------- close ---------- */}
      {/* Left-aligned like every section above it. Centring only the last one
          made the page look like it changed its mind at the bottom; the
          actions move to the right column so the row is balanced instead. */}
      <section className="mx-auto w-full max-w-[1180px] px-5 pb-28 sm:px-10">
        <div className="grid gap-x-14 gap-y-9 border-t-[3px] border-border pt-12 lg:grid-cols-[1fr_auto] lg:items-end">
          <div>
            <h2 className="max-w-[20ch] text-balance font-display text-[clamp(1.75rem,3.4vw,2.5rem)] font-bold leading-[1.08] tracking-[-0.025em] text-foreground">
              Clone it, run one command, type one sentence.
            </h2>
            <p className="mt-5 max-w-[52ch] text-pretty text-[1.0625rem] leading-relaxed text-muted-foreground">
              All of it happens on your machine. If it does not work in the
              first minute, that is a bug worth filing.
            </p>
          </div>

          <div className="lg:text-right">
            <div className="flex flex-wrap items-center gap-3 lg:justify-end">
              <button
                onClick={() => setShowSignUp(true)}
                className="rounded-lg bg-primary px-6 py-3 text-sm font-bold text-primary-foreground transition-opacity hover:opacity-90"
              >
                Get started
              </button>
              <a
                href="https://github.com/Sma1lboy/codefox"
                target="_blank"
                rel="noopener noreferrer"
                className="rounded-lg border border-border px-6 py-3 text-sm font-medium text-foreground transition-colors hover:border-primary"
              >
                Read the source
              </a>
            </div>
            <p className="mt-6 font-mono text-xs text-muted-foreground">
              MIT · Node 18+ · macOS, Linux, WSL
            </p>
          </div>
        </div>
      </section>

      <AuthChoiceModal
        isOpen={showAuthChoice}
        onClose={() => setShowAuthChoice(false)}
        onSignUpClick={() => {
          setShowAuthChoice(false);
          setTimeout(() => setShowSignUp(true), 100);
        }}
        onSignInClick={() => {
          setShowAuthChoice(false);
          setTimeout(() => setShowSignIn(true), 100);
        }}
      />
      <SignInModal isOpen={showSignIn} onClose={() => setShowSignIn(false)} />
      <SignUpModal isOpen={showSignUp} onClose={() => setShowSignUp(false)} />
    </div>
  );
}
